// Official 2026 Academic Year NCTB Secondary School (Class 9-10 & SSC) Textbook Database
// Source: https://nctb.gov.bd/pages/static-pages/695b99afc4774958d7b70612

export const NCTB_CLASSES = [
  {
    id: 'class-6',
    nameBn: '৬ষ্ঠ শ্রেণি (Class 6)',
    nameEn: 'Class 6',
    levelBn: 'নিম্ন মাধ্যমিক (NCTB)',
    levelEn: 'Junior Secondary',
    subjects: [
      { id: 'bangla-6', nameBn: 'বাংলা সাহিত্য ও আনন্দপাঠ', nameEn: 'Bangla Literature', group: 'আবশ্যিক', icon: '📚' },
      { id: 'math-6', nameBn: 'গণিত', nameEn: 'Mathematics', group: 'আবশ্যিক', icon: '📐' },
      { id: 'science-6', nameBn: 'বিজ্ঞান', nameEn: 'Science', group: 'বিজ্ঞান', icon: '🔬' },
      { id: 'english-6', nameBn: 'English For Today', nameEn: 'English', group: 'আবশ্যিক', icon: '📖' },
      { id: 'ict-6', nameBn: 'তথ্য ও যোগাযোগ প্রযুক্তি', nameEn: 'ICT', group: 'আবশ্যিক', icon: '💻' },
      { id: 'bgs-6', nameBn: 'বাংলাদেশ ও বিশ্বপরিচয়', nameEn: 'Bangladesh & Global Studies', group: 'আবশ্যিক', icon: '🌏' },
      { id: 'islam-6', nameBn: 'ইসলাম ও নৈতিক শিক্ষা', nameEn: 'Islamic Studies', group: 'ধর্ম শিক্ষা', icon: '🕌' },
    ]
  },
  {
    id: 'class-7',
    nameBn: '৭ম শ্রেণি (Class 7)',
    nameEn: 'Class 7',
    levelBn: 'নিম্ন মাধ্যমিক (NCTB)',
    levelEn: 'Junior Secondary',
    subjects: [
      { id: 'bangla-7', nameBn: 'বাংলা সাহিত্য ও ব্যাকরণ', nameEn: 'Bangla', group: 'আবশ্যিক', icon: '📚' },
      { id: 'math-7', nameBn: 'গণিত', nameEn: 'Mathematics', group: 'আবশ্যিক', icon: '📐' },
      { id: 'science-7', nameBn: 'বিজ্ঞান ও অনুসন্ধান', nameEn: 'Science & Inquiry', group: 'বিজ্ঞান', icon: '🔬' },
      { id: 'english-7', nameBn: 'English For Today', nameEn: 'English', group: 'আবশ্যিক', icon: '📖' },
      { id: 'ict-7', nameBn: 'ডিজিটাল প্রযুক্তি ও আইসিটি', nameEn: 'Digital Tech', group: 'আবশ্যিক', icon: '💻' },
      { id: 'bgs-7', nameBn: 'বাংলাদেশ ও বিশ্বপরিচয়', nameEn: 'Bangladesh & Global Studies', group: 'আবশ্যিক', icon: '🌏' },
    ]
  },
  {
    id: 'class-8',
    nameBn: '৮ম শ্রেণি (Class 8)',
    nameEn: 'Class 8',
    levelBn: 'জুনিয়র স্কুল (NCTB)',
    levelEn: 'Junior School',
    subjects: [
      { id: 'bangla-8', nameBn: 'বাংলা সাহিত্য ও সহপাঠ', nameEn: 'Bangla Literature', group: 'আবশ্যিক', icon: '📚' },
      { id: 'math-8', nameBn: 'গণিত', nameEn: 'Mathematics', group: 'আবশ্যিক', icon: '📐' },
      { id: 'science-8', nameBn: 'বিজ্ঞান (পরমাণু ও মহাকর্ষ)', nameEn: 'General Science', group: 'বিজ্ঞান', icon: '🔬' },
      { id: 'english-8', nameBn: 'English Grammar & Comp', nameEn: 'English', group: 'আবশ্যিক', icon: '📖' },
      { id: 'ict-8', nameBn: 'তথ্য ও যোগাযোগ প্রযুক্তি', nameEn: 'ICT', group: 'আবশ্যিক', icon: '💻' },
      { id: 'bgs-8', nameBn: 'বাংলাদেশ ও বিশ্বপরিচয়', nameEn: 'Bangladesh & Global Studies', group: 'আবশ্যিক', icon: '🌏' },
    ]
  },
  {
    id: 'class-9',
    nameBn: '৯ম-১০ম শ্রেণি (SSC)',
    nameEn: 'Class 9-10 (SSC)',
    levelBn: 'মাধ্যমিক স্তরের শিক্ষাক্রম ২০২৬ (NCTB Board)',
    levelEn: 'Secondary School Certificate 2026',
    subjects: [
      // 1. আবশ্যিক বিষয়সমূহ (Compulsory / Core Subjects)
      { id: 'bangla-sahitya', nameBn: 'বাংলা সাহিত্য', nameEn: 'Bangla Literature', group: 'আবশ্যিক', icon: '📚' },
      { id: 'bangla-sohopath', nameBn: 'বাংলা সহপাঠ', nameEn: 'Bangla Sohopath', group: 'আবশ্যিক', icon: '📖' },
      { id: 'bangla-grammar', nameBn: 'বাংলা ভাষার ব্যাকরণ ও নির্মিতি', nameEn: 'Bangla Grammar & Comp', group: 'আবশ্যিক', icon: '✍️' },
      { id: 'english-today', nameBn: 'English For Today', nameEn: 'English For Today', group: 'আবশ্যিক', icon: '📘' },
      { id: 'english-grammar', nameBn: 'English Grammar and Composition', nameEn: 'English Grammar', group: 'আবশ্যিক', icon: '📝' },
      { id: 'general-math', nameBn: 'গণিত (সাধারণ)', nameEn: 'Mathematics', group: 'আবশ্যিক', icon: '📐' },
      { id: 'ict', nameBn: 'তথ্য ও যোগাযোগ প্রযুক্তি', nameEn: 'ICT', group: 'আবশ্যিক', icon: '💻' },
      { id: 'bgs', nameBn: 'বাংলাদেশ ও বিশ্বপরিচয়', nameEn: 'Bangladesh & Global Studies', group: 'আবশ্যিক', icon: '🌏' },
      { id: 'general-science', nameBn: 'বিজ্ঞান (সাধারণ)', nameEn: 'General Science', group: 'আবশ্যিক', icon: '🔬' },
      { id: 'career-edu', nameBn: 'ক্যারিয়ার শিক্ষা', nameEn: 'Career Education', group: 'আবশ্যিক', icon: '🎯' },
      { id: 'physical-edu', nameBn: 'শারীরিক শিক্ষা ও স্বাস্থ্যবিজ্ঞান', nameEn: 'Physical Education & Health', group: 'আবশ্যিক', icon: '🏃' },
      { id: 'arts-crafts', nameBn: 'চারু ও কারুকলা', nameEn: 'Arts and Crafts', group: 'আবশ্যিক', icon: '🎨' },

      // 2. বিজ্ঞান বিভাগ (Science Group)
      { id: 'physics', nameBn: 'পদার্থবিজ্ঞান', nameEn: 'Physics', group: 'বিজ্ঞান', icon: '⚛️' },
      { id: 'chemistry', nameBn: 'রসায়ন', nameEn: 'Chemistry', group: 'বিজ্ঞান', icon: '🧪' },
      { id: 'biology', nameBn: 'জীববিজ্ঞান', nameEn: 'Biology', group: 'বিজ্ঞান', icon: '🧬' },
      { id: 'higher-math', nameBn: 'উচ্চতর গণিত', nameEn: 'Higher Mathematics', group: 'বিজ্ঞান', icon: '📊' },

      // 3. ব্যবসায় শিক্ষা বিভাগ (Business Studies / Commerce Group)
      { id: 'accounting', nameBn: 'হিসাববিজ্ঞান', nameEn: 'Accounting', group: 'ব্যবসায় শিক্ষা', icon: '📑' },
      { id: 'finance-banking', nameBn: 'ফিন্যান্স ও ব্যাংকিং', nameEn: 'Finance and Banking', group: 'ব্যবসায় শিক্ষা', icon: '💳' },
      { id: 'business-ent', nameBn: 'ব্যবসায় উদ্যোগ', nameEn: 'Business Entrepreneurship', group: 'ব্যবসায় শিক্ষা', icon: '🏢' },

      // 4. মানবিক বিভাগ (Humanities / Arts Group)
      { id: 'history-bd', nameBn: 'বাংলাদেশের ইতিহাস ও বিশ্বসভ্যতা', nameEn: 'History of BD & World', group: 'মানবিক', icon: '🏛️' },
      { id: 'geography-env', nameBn: 'ভূগোল ও পরিবেশ', nameEn: 'Geography and Environment', group: 'মানবিক', icon: '🗺️' },
      { id: 'civics-citizen', nameBn: 'পৌরনীতি ও নাগরিকতা', nameEn: 'Civics and Citizenship', group: 'মানবিক', icon: '⚖️' },
      { id: 'economics', nameBn: 'অর্থনীতি', nameEn: 'Economics', group: 'মানবিক', icon: '📈' },

      // 5. ধর্ম ও নৈতিক শিক্ষা (Religion Studies)
      { id: 'islam-studies', nameBn: 'ইসলাম ও নৈতিক শিক্ষা', nameEn: 'Islamic Studies', group: 'ধর্ম শিক্ষা', icon: '🕌' },
      { id: 'hindu-studies', nameBn: 'হিন্দুধর্ম ও নৈতিক শিক্ষা', nameEn: 'Hindu Religion Studies', group: 'ধর্ম শিক্ষা', icon: '🕉️' },
      { id: 'buddhist-studies', nameBn: 'বৌদ্ধধর্ম ও নৈতিক শিক্ষা', nameEn: 'Buddhist Religion Studies', group: 'ধর্ম শিক্ষা', icon: '☸️' },
      { id: 'christian-studies', nameBn: 'খ্রিস্টধর্ম ও নৈতিক শিক্ষা', nameEn: 'Christian Religion Studies', group: 'ধর্ম শিক্ষা', icon: '✝️' },

      // 6. ঐচ্ছিক বিষয় (Optional Subjects)
      { id: 'agri-studies', nameBn: 'কৃষিশিক্ষা', nameEn: 'Agriculture Studies', group: 'ঐচ্ছিক', icon: '🌱' },
      { id: 'home-science', nameBn: 'গার্হস্থ্যবিজ্ঞান', nameEn: 'Home Science', group: 'ঐচ্ছিক', icon: '🏡' },
      { id: 'arabic', nameBn: 'আরবি', nameEn: 'Arabic', group: 'ঐচ্ছিক', icon: '📜' },
      { id: 'music', nameBn: 'সংগীত', nameEn: 'Music', group: 'ঐচ্ছিক', icon: '🎵' },
    ]
  }
];

// Comprehensive Pre-loaded NCTB Textbook Chapters & Study Notes
export const NCTB_OFFICIAL_BOOK_NOTES = [
  // 1. বাংলা সাহিত্য (Bangla Sahitya)
  {
    id: 'note-bs-1',
    title: 'বাংলা সাহিত্য: ‘বই পড়া’ ও ‘শিক্ষা ও মনুষ্যত্ব’ সারসংক্ষেপ',
    subject: 'Bangla Literature',
    subjectBn: 'বাংলা সাহিত্য',
    subjectId: 'bangla-sahitya',
    classId: 'class-9',
    summary: 'প্রমথ চৌধুরীর ‘বই পড়া’ প্রবন্ধে সাহিত্যের আবশ্যকতা ও লাইব্রেরির গুরুত্ব তুলে ধরা হয়েছে। মোতাহের হোসেন চৌধুরীর ‘শিক্ষা ও মনুষ্যত্ব’ প্রবন্ধে মানুষের জীবসত্তা থেকে মানবসত্তায় উত্তরণের পথ নির্দেশ করা হয়েছে।',
    formula: 'শিক্ষা = জীবসত্তা (অন্ন-বস্ত্র) + মানবসত্তা (মনুষ্যত্ব)',
    scannedImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80',
    date: 'Today, 10:00 AM',
    podcastDuration: '3:20 min',
    tags: ['Class 9-10', 'Bangla', 'NCTB', 'Prose'],
    hasAudio: true,
  },
  // 2. বাংলা সহপাঠ (Bangla Sohopath)
  {
    id: 'note-bsp-1',
    title: 'বাংলা সহপাঠ: ‘কাকতাড়ুয়া’ উপন্যাস ও ‘বহিপীর’ নাটক',
    subject: 'Bangla Sohopath',
    subjectBn: 'বাংলা সহপাঠ',
    subjectId: 'bangla-sohopath',
    classId: 'class-9',
    summary: 'সেলিনা হোসেনের ‘কাকতাড়ুয়া’ উপন্যাসে কিশোর বুধার অসীম সাহসিকতায় পাকিস্তানি ক্যাম্প উড়িয়ে দেওয়ার কাহিনী বর্ণিত হয়েছে। সৈয়দ ওয়ালীউল্লাহর ‘বহিপীর’ নাটকে তাহেরার মাধ্যমে কুসংস্কার ও বৃদ্ধ পীরের সাথে অসম বিবাহের দৃঢ় প্রতিবাদ প্রকাশ পেয়েছে।',
    formula: 'উপন্যাস: কাকতাড়ুয়া (বুধা) | নাটক: বহিপীর (তাহেরা ও হাতেম আলী)',
    scannedImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    date: 'Today, 11:20 AM',
    podcastDuration: '3:15 min',
    tags: ['Class 9-10', 'Bangla', 'Sohopath', 'Novel', 'Drama'],
    hasAudio: true,
  },
  // 3. বাংলা ভাষার ব্যাকরণ ও নির্মিতি
  {
    id: 'note-bg-1',
    title: 'বাংলা ব্যাকরণ: ধ্বনিতত্ত্ব, সন্ধি ও সমাস নির্ণয়',
    subject: 'Bangla Grammar & Comp',
    subjectBn: 'বাংলা ভাষার ব্যাকরণ ও নির্মিতি',
    subjectId: 'bangla-grammar',
    classId: 'class-9',
    summary: 'সন্ধি: পরস্পর সন্নিহিত দুটি ধ্বনির মিলন। সমাস: পরস্পর অর্থসঙ্গতিবিশিষ্ট একাধিক পদের এক পদে পরিণত হওয়া (দ্বন্দ্ব, দ্বিগু, কর্মধারয়, তৎপুরুষ, বহুব্রীহি ও অব্যয়ীভাব)।',
    formula: 'বিদ্যা + আলয় = বিদ্যালয় | সিংহাসন = সিংহ চিহ্নিত আসন (কর্মধারয়)',
    scannedImage: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
    date: 'Yesterday, 3:45 PM',
    podcastDuration: '2:50 min',
    tags: ['Class 9-10', 'Bangla', 'Grammar', 'Sandhi', 'Samas'],
    hasAudio: true,
  },
  // 4. English For Today
  {
    id: 'note-eng-1',
    title: 'English For Today: Unit 1 - Good Citizens & Pastimes',
    subject: 'English For Today',
    subjectBn: 'English For Today',
    subjectId: 'english-today',
    classId: 'class-9',
    summary: 'Key themes from Unit 1: Duties and responsibilities of a good citizen, knowledge of constitution, obeying laws, environmental awareness and healthy pastimes.',
    formula: 'Citizen Responsibilities = Civic Duty + Rule of Law + Social Awareness',
    scannedImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    date: 'Yesterday, 5:10 PM',
    podcastDuration: '3:05 min',
    tags: ['Class 9-10', 'English', 'Unit 1', 'NCTB'],
    hasAudio: true,
  },
  // 5. গণিত (সাধারণ)
  {
    id: 'note-math-1',
    title: 'সাধারণ গণিত: অধ্যায় ৩ - বীজগাণিতিক রাশি ও উৎপাদক',
    subject: 'Mathematics',
    subjectBn: 'গণিত (সাধারণ)',
    subjectId: 'general-math',
    classId: 'class-9',
    summary: 'বর্গ ও ঘনের সূত্রাবলী: (a + b)² = a² + 2ab + b² এবং মান নির্ণয়ের অনুসিদ্ধান্ত: a² + b² = (a + b)² - 2ab = (a - b)² + 2ab। উৎপাদক বিশ্লেষণের কমন নিয়মাবলী।',
    formula: 'a² + b² = (a + b)² - 2ab | 4ab = (a + b)² - (a - b)²',
    scannedImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    date: 'Yesterday, 4:30 PM',
    podcastDuration: '3:10 min',
    tags: ['Class 9-10', 'Math', 'Algebra', 'Formulas'],
    hasAudio: true,
  },
  // 6. পদার্থবিজ্ঞান (Physics)
  {
    id: 'note-phys-1',
    title: 'পদার্থবিজ্ঞান: অধ্যায় ৩ - বল, জড়তা ও নিউটনের গতিসূত্রাবলী',
    subject: 'Physics',
    subjectBn: 'পদার্থবিজ্ঞান',
    subjectId: 'physics',
    classId: 'class-9',
    summary: '১. জড়তা ও বলের সংজ্ঞা। ২. নিউটনের ২য় সূত্র: প্রযুক্ত বল ভরবেগের পরিবর্তনের হারের সমানুপাতিক (F = ma)। ৩. ভরবেগের সংরক্ষণশীলতা নীতি: m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂।',
    formula: 'F = m · a | m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂',
    scannedImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    date: 'Today, 10:15 AM',
    podcastDuration: '2:45 min',
    tags: ['Class 9-10', 'Physics', 'Motion', 'Force', 'Newton'],
    hasAudio: true,
  },
  // 7. রসায়ন (Chemistry)
  {
    id: 'note-chem-1',
    title: 'রসায়ন: অধ্যায় ৩ ও ৪ - পরমাণুর গঠন ও পর্যায় সারণি',
    subject: 'Chemistry',
    subjectBn: 'রসায়ন',
    subjectId: 'chemistry',
    classId: 'class-9',
    summary: 'বোর পরমাণু মডেলের মূল স্বীকার্য। কক্ষপথে ইলেকট্রন ধারণক্ষমতা ২n²। পর্যায় সারণিতে বাম থেকে ডানে গেলে পারমাণবিক ব্যাসার্ধ কমে এবং আয়নীকরণ শক্তি বৃদ্ধি পায়।',
    formula: 'Shell Capacity = 2n² (K=2, L=8, M=18, N=32)',
    scannedImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    date: '14 Aug, 8:20 PM',
    podcastDuration: '3:30 min',
    tags: ['Class 9-10', 'Chemistry', 'Atom', 'Periodic Table'],
    hasAudio: true,
  },
  // 8. জীববিজ্ঞান (Biology)
  {
    id: 'note-bio-1',
    title: 'জীববিজ্ঞান: অধ্যায় ২ ও ৪ - জীবকোষ, টিস্যু ও জীবনীশক্তি',
    subject: 'Biology',
    subjectBn: 'জীববিজ্ঞান',
    subjectId: 'biology',
    classId: 'class-9',
    summary: 'উদ্ভিদ ও প্রাণিকোষের পার্থক্য। মাইটোকনড্রিয়াকে কোষের পাওয়ার হাউস বলা হয় (ATP তৈরি)। সালোকসংশ্লেষণের আলোক ও অন্ধকার পর্যায়ের জৈব রাসায়নিক বিক্রিয়া।',
    formula: '6CO₂ + 12H₂O + Light → C₆H₁₂O₆ + 6O₂ + 6H₂O (Photosynthesis)',
    scannedImage: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=600&auto=format&fit=crop&q=80',
    date: '13 Aug, 2:15 PM',
    podcastDuration: '3:15 min',
    tags: ['Class 9-10', 'Biology', 'Cell', 'ATP', 'Photosynthesis'],
    hasAudio: true,
  },
  // 9. উচ্চতর গণিত (Higher Math)
  {
    id: 'note-hmath-1',
    title: 'উচ্চতর গণিত: অধ্যায় ৮ - ত্রিকোণমিতি ও বৃত্তাকার পরিমাপ',
    subject: 'Higher Mathematics',
    subjectBn: 'উচ্চতর গণিত',
    subjectId: 'higher-math',
    classId: 'class-9',
    summary: 'রেডিয়ান কোণ একটি ধ্রুব কোণ (১ রেডিয়ান = ১৮০°/π)। বৃত্তচাপের দৈর্ঘ্য s = rθ (যেখানে θ রেডিয়ানে)। চতুর্ভাগে ত্রিকোণমিতিক চিহ্নের পরিবর্তন (All, Sin, Tan, Cos)।',
    formula: 's = r · θ | 1 Radian = 180° / π ≈ 57.2958°',
    scannedImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    date: '12 Aug, 6:40 PM',
    podcastDuration: '2:55 min',
    tags: ['Class 9-10', 'Higher Math', 'Trigonometry', 'Radian'],
    hasAudio: true,
  },
  // 10. হিসাববিজ্ঞান (Accounting)
  {
    id: 'note-acc-1',
    title: 'হিসাববিজ্ঞান: অধ্যায় ৩ ও ৬ - দুতরফা দাখিলা ও জাবেদা প্রস্তুতকরণ',
    subject: 'Accounting',
    subjectBn: 'হিসাববিজ্ঞান',
    subjectId: 'accounting',
    classId: 'class-9',
    summary: 'হিসাব সমীকরণ: সম্পদ = দায় + মালিকানা স্বত্ব (A = L + E)। ডেবিট ও ক্রেডিট নির্ণয়ের সূত্র: সম্পদ ও ব্যয় বাড়লে ডেবিট, কমলে ক্রেডিট; দায়, আয় ও মূলধন বাড়লে ক্রেডিট।',
    formula: 'Assets (A) = Liabilities (L) + Owner\'s Equity (E)',
    scannedImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    date: '11 Aug, 1:30 PM',
    podcastDuration: '3:40 min',
    tags: ['Class 9-10', 'Commerce', 'Accounting', 'Debit Credit', 'Equation'],
    hasAudio: true,
  },
  // 11. ফিন্যান্স ও ব্যাংকিং (Finance & Banking)
  {
    id: 'note-fin-1',
    title: 'ফিন্যান্স ও ব্যাংকিং: অধ্যায় ৩ - অর্থের সময়মূল্য (Time Value of Money)',
    subject: 'Finance and Banking',
    subjectBn: 'ফিন্যান্স ও ব্যাংকিং',
    subjectId: 'finance-banking',
    classId: 'class-9',
    summary: 'অর্থের বর্তমান মূল্য ও ভবিষ্যৎ মূল্য নির্ণয়। চক্রবৃদ্ধিকরণ পদ্ধতি ও বাট্টাকরণ প্রক্রিয়া। রুল-৭২ প্রয়োগ করে বিনিয়োগ দ্বিগুণ হওয়ার সময় নির্ণয়।',
    formula: 'FV = PV(1 + i)ⁿ | PV = FV / (1 + i)ⁿ',
    scannedImage: 'https://images.unsplash.com/photo-1565372195458-9de0b320ef04?w=600&auto=format&fit=crop&q=80',
    date: '10 Aug, 11:00 AM',
    podcastDuration: '3:00 min',
    tags: ['Class 9-10', 'Commerce', 'Finance', 'Time Value of Money'],
    hasAudio: true,
  },
  // 12. তথ্য ও যোগাযোগ প্রযুক্তি (ICT)
  {
    id: 'note-ict-1',
    title: 'তথ্য ও যোগাযোগ প্রযুক্তি: অধ্যায় ১ ও ৩ - ডিজিটাল নিরাপত্তা ও ই-লার্নিং',
    subject: 'ICT',
    subjectBn: 'তথ্য ও যোগাযোগ প্রযুক্তি',
    subjectId: 'ict',
    classId: 'class-9',
    summary: 'তথ্যপ্রযুক্তির বিকাশ ও ডিজিটাল বাংলাদেশ। ইন্টারনেটের নিরাপদ ব্যবহার, সাইবার অপরাধ প্রতিরোধ, পাসওয়ার্ড নিরাপত্তা ও কপিরাইট আইন।',
    formula: 'Strong Password = Upper + Lower + Number + Symbol (Min 8 chars)',
    scannedImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    date: '09 Aug, 4:20 PM',
    podcastDuration: '2:40 min',
    tags: ['Class 9-10', 'ICT', 'Cyber Security', 'Internet'],
    hasAudio: true,
  },
  // 13. ইতিহাস ও বিশ্বসভ্যতা (History)
  {
    id: 'note-hist-1',
    title: 'বাংলাদেশের ইতিহাস ও বিশ্বসভ্যতা: অধ্যায় ১২ - ১৯৭১ সালের মুক্তিযুদ্ধ',
    subject: 'History of BD & World',
    subjectBn: 'বাংলাদেশের ইতিহাস ও বিশ্বসভ্যতা',
    subjectId: 'history-bd',
    classId: 'class-9',
    summary: '৭ই মার্চের ঐতিহাসিক ভাষণ ও স্বাধীনতা ঘোষণা। ২৫শে মার্চের গণহত্যা ‘অপারেশন সার্চলাইট’। মুজিবনগর সরকার গঠন (১০ এপ্রিল ১৯৭১) ও ১৬ ডিসেম্বর বিজয় অর্জন।',
    formula: 'মুক্তিযুদ্ধ ১৯৭১ = ৭ই মার্চ ভাষণ + মুজিবনগর সরকার + ১৬ ডিসেম্বর বিজয়',
    scannedImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    date: '08 Aug, 10:50 AM',
    podcastDuration: '3:45 min',
    tags: ['Class 9-10', 'Humanities', 'History', 'Liberation War 1971'],
    hasAudio: true,
  },
  // 14. ভূগোল ও পরিবেশ (Geography)
  {
    id: 'note-geo-1',
    title: 'ভূগোল ও পরিবেশ: অধ্যায় ২ - মহাবিশ্ব, অক্ষাংশ, দ্রাঘিমাংশ ও সময় নির্ণয়',
    subject: 'Geography and Environment',
    subjectBn: 'ভূগোল ও পরিবেশ',
    subjectId: 'geography-env',
    classId: 'class-9',
    summary: '১° দ্রাঘিমার পার্থক্যের জন্য সময়ের পার্থক্য ৪ মিনিট। গ্রিনিচ প্রমাণ সময় (GMT) এর চেয়ে বাংলাদেশ সময় ৬ ঘণ্টা এগিয়ে (+6 GMT)। দিবারাত্রির হ্রাস-বৃদ্ধি।',
    formula: '1° Longitude = 4 Minutes Difference | BD Time = GMT + 6 Hours',
    scannedImage: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=600&auto=format&fit=crop&q=80',
    date: '07 Aug, 3:15 PM',
    podcastDuration: '3:10 min',
    tags: ['Class 9-10', 'Humanities', 'Geography', 'Longitude', 'Time'],
    hasAudio: true,
  },
  // 15. ইসলাম ও নৈতিক শিক্ষা (Islamic Studies)
  {
    id: 'note-isl-1',
    title: 'ইসলাম ও নৈতিক শিক্ষা: অধ্যায় ১ ও ৩ - আকাইদ ও ইবাদতের সামাজিক প্রভাব',
    subject: 'Islamic Studies',
    subjectBn: 'ইসলাম ও নৈতিক শিক্ষা',
    subjectId: 'islam-studies',
    classId: 'class-9',
    summary: 'তাওহীদ, রিসালাত ও আখিরাতের তাৎপর্য। নামায, রোজা ও যাকাতের সামাজিক সাম্য ও ভ্রাতৃত্ব প্রতিষ্ঠায় ভূমিকা। সততা ও আমানতদারিতা রক্ষা করা।',
    formula: 'ঈমান = তাওহীদ (একত্ববাদ) + রিসালাত (নবুয়ত) + আখিরাত (পরকাল)',
    scannedImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&auto=format&fit=crop&q=80',
    date: '06 Aug, 8:00 AM',
    podcastDuration: '3:00 min',
    tags: ['Class 9-10', 'Islam', 'Aqeedah', 'Ibadah', 'Ethics'],
    hasAudio: true,
  },
  // 16. পৌরনীতি ও নাগরিকতা (Civics & Citizenship)
  {
    id: 'note-civ-1',
    title: 'পৌরনীতি ও নাগরিকতা: অধ্যায় ৫ ও ৬ - বাংলাদেশ সংবিধান ও সরকার ব্যবস্থা',
    subject: 'Civics & Citizenship',
    subjectBn: 'পৌরনীতি ও নাগরিকতা',
    subjectId: 'civics-citizenship',
    classId: 'class-9',
    summary: '১৯৭২ সালের ৪ নভেম্বর গণপরিষদে সংবিধান গৃহীত ও ১৬ ডিসেম্বর কার্যকর। ১৫৩টি অনুচ্ছেদ ও ৪ মূলনীতি। সরকারের ৩টি বিভাগ: আইন বিভাগ (জাতীয় সংসদ ৩৫০ আসন), শাসন বিভাগ ও সুপ্রিম কোর্ট।',
    formula: 'সংবিধান ৪ মূলনীতি = জাতীয়তাবাদ + সমাজতন্ত্র + গণতন্ত্র + ধর্মনিরপেক্ষতা | সংসদ = ৩৫০ আসন',
    scannedImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    date: '05 Aug, 10:15 AM',
    podcastDuration: '3:10 min',
    tags: ['Class 9-10', 'Humanities', 'Civics', 'Constitution', 'Government'],
    hasAudio: true,
  },
  // 17. ব্যবসায় উদ্যোগ (Business Entrepreneurship)
  {
    id: 'note-be-1',
    title: 'ব্যবসায় উদ্যোগ: অধ্যায় ৬ ও ৮ - ব্যবসায় পরিকল্পনা ও প্রাতিষ্ঠানিক ব্যবস্থাপনা',
    subject: 'Business Entrepreneurship',
    subjectBn: 'ব্যবসায় উদ্যোগ',
    subjectId: 'business-ent',
    classId: 'class-9',
    summary: 'ব্যবসা পরিকল্পনার উপাদান ও SWOT বিশ্লেষণ (Strengths, Weaknesses, Opportunities, Threats)। আধুনিক ব্যবস্থাপনার ৭টি মৌলিক কার্যাবলী এবং হেনরি ফেয়ল এর ১৪টি মূলনীতি।',
    formula: 'SWOT = Strengths + Weaknesses + Opportunities + Threats | POSDCORB',
    scannedImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80',
    date: '04 Aug, 2:40 PM',
    podcastDuration: '3:00 min',
    tags: ['Class 9-10', 'Commerce', 'Business', 'Entrepreneurship', 'Management'],
    hasAudio: true,
  },
  // 18. অর্থনীতি (Economics)
  {
    id: 'note-eco-1',
    title: 'অর্থনীতি: অধ্যায় ৩ ও ৬ - চাহিদা-জোগান ভারসাম্য ও জাতীয় আয় পরিমাপ',
    subject: 'Economics',
    subjectBn: 'অর্থনীতি',
    subjectId: 'economics',
    classId: 'class-9',
    summary: 'চাহিদা ও জোগানের ছেদবিন্দুতে ভারসাম্য দাম ও পরিমাণ নির্ধারণ (Qd = Qs)। মোট দেশজ উৎপাদন (GDP) ও মোট জাতীয় উৎপাদন (GNP) পরিমাপের ৩টি পদ্ধতি এবং মাথাপিছু আয় নির্ণয়।',
    formula: 'ভারসাম্য: Qd = Qs | GDP vs GNP | Y = C + I + G + (X - M)',
    scannedImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop&q=80',
    date: '03 Aug, 11:30 AM',
    podcastDuration: '3:20 min',
    tags: ['Class 9-10', 'Humanities', 'Economics', 'Demand', 'Supply', 'GDP'],
    hasAudio: true,
  },
  // 19. হিন্দুধর্ম ও নৈতিক শিক্ষা (Hindu Religion)
  {
    id: 'note-hin-1',
    title: 'হিন্দুধর্ম ও নৈতিক শিক্ষা: অধ্যায় ৩ ও ৮ - গীতার কর্মযোগ ও স্বামী বিবেকানন্দ',
    subject: 'Hindu Religion Studies',
    subjectBn: 'হিন্দুধর্ম ও নৈতিক শিক্ষা',
    subjectId: 'hindu-studies',
    classId: 'class-9',
    summary: 'শ্রীমদ্ভগবদ্গীতার ১৮ অধ্যায় ও ৭০০ শ্লোক—নিষ্কাম কর্মযোগ ("কর্মণ্যেবাধিকারস্তে মা ফলেষু কদাচন")। ১৮৯৩ সালে শিকাগো বিশ্বধর্ম সম্মেলনে স্বামী বিবেকানন্দের সার্বজনীন মানবপ্রেমের জয়গান ও রামকৃষ্ণ মিশন।',
    formula: 'গীতা = নিষ্কাম কর্মযোগ | "জীবে প্রেম করে যেই জন, সেই জন সেবিছে ঈশ্বর" | যত মত তত পথ',
    scannedImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    date: '02 Aug, 09:15 AM',
    podcastDuration: '3:15 min',
    tags: ['Class 9-10', 'Religion', 'Hinduism', 'Gita', 'Vivekananda'],
    hasAudio: true,
  },
  // 20. বৌদ্ধধর্ম ও নৈতিক শিক্ষা (Buddhist Religion)
  {
    id: 'note-bud-1',
    title: 'বৌদ্ধধর্ম ও নৈতিক শিক্ষা: অধ্যায় ২ ও ১১ - চতুরার্য সত্য ও বিশ্বশান্তিতে মৈত্রীভাবনা',
    subject: 'Buddhist Religion Studies',
    subjectBn: 'বৌদ্ধধর্ম ও নৈতিক শিক্ষা',
    subjectId: 'buddhist-studies',
    classId: 'class-9',
    summary: 'চতুরার্য সত্য ও অষ্টাঙ্গিক মার্গ (শীল, সমাধি, প্রজ্ঞা)। "সব্বে সত্তা সুখিতা হোন্তু"—জগতের সকল জীবের মঙ্গল কামনায় মৈত্রীভাবনা এবং অহিংসার মধ্য দিয়ে বিশ্বশান্তি প্রতিষ্ঠা।',
    formula: 'চতুরার্য সত্য ➔ অষ্টাঙ্গিক মার্গ ➔ নির্বাণ | "সব্বে সত্তা সুখিতা হোন্তু"',
    scannedImage: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?w=600&auto=format&fit=crop&q=80',
    date: '01 Aug, 10:45 AM',
    podcastDuration: '3:05 min',
    tags: ['Class 9-10', 'Religion', 'Buddhism', 'Tripitaka', 'Metta'],
    hasAudio: true,
  }
];

export const NCTB_PRESET_SCANS = [
  {
    id: 'scan-c9-bangla-sohopath',
    classId: 'class-9',
    subject: 'Bangla Sohopath',
    subjectBn: 'বাংলা সহপাঠ',
    titleBn: '৯ম-১০ম বাংলা সহপাঠ: ‘কাকতাড়ুয়া’ ও ‘বহিপীর’',
    titleEn: 'Class 9-10 Bangla Sohopath: Kaktarua & Bohipir',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    detectedTextBn: 'বাংলা সহপাঠ: সেলিনা হোসেনের ‘কাকতাড়ুয়া’ উপন্যাস (মুক্তিযোদ্ধা বুধা) এবং সৈয়দ ওয়ালীউল্লাহর ‘বহিপীর’ নাটক (তাহেরা ও কুসংস্কার প্রতিরোধ)।',
    detectedTextEn: 'Bangla Sohopath: Selina Hossain\'s "Kaktarua" novel and Syed Waliullah\'s "Bohipir" play.',
    solutionBn: '১. কাকতাড়ুয়া: মুক্তিযুদ্ধভিত্তিক উপন্যাস। কিশোর বুধা সাহসী ভূমিকা রেখে পাকিস্তানি হানাদার ক্যাম্প মাইন দিয়ে ধ্বংস করে।\n২. বহিপীর: কুসংস্কার ও অসম বিবাহের বিরুদ্ধে নারীর দৃঢ় প্রতিবাদী চরিত্র তাহেরা।\n৩. বোর্ড পরীক্ষায় অনুধাবন ও প্রয়োগমূলক প্রশ্নের জন্য মূল চরিত্র ও সংলাপ অত্যন্ত গুরুত্বপূর্ণ।',
    solutionEn: '1. Kaktarua: Liberation War novel showing teenage heroism of Budha.\n2. Bohipir: Strong social drama against superstitious forced marriages.\n3. Essential character dialogues & themes for SSC board exam.',
    formula: 'উপন্যাস: কাকতাড়ুয়া | নাটক: বহিপীর',
    chapterBn: 'বাংলা সহপাঠ (উপন্যাস ও নাটক)',
    chapterEn: 'Bangla Sohopath'
  },
  {
    id: 'scan-c9-phys',
    classId: 'class-9',
    subject: 'Physics',
    subjectBn: 'পদার্থবিজ্ঞান',
    titleBn: '৯ম-১০ম পদার্থবিজ্ঞান: বল, গতি ও নিউটনের ২য় সূত্র',
    titleEn: 'Class 9-10 Physics: Motion & Newton\'s 2nd Law',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    detectedTextBn: 'অধ্যায় ৩: বল ও গতি। সূত্র: বস্তুর ভরবেগের পরিবর্তনের হার তার ওপর প্রযুক্ত বলের সমানুপাতিক। F = ma.',
    detectedTextEn: 'Chapter 3: Force & Motion. Law: Rate of change of momentum is proportional to applied force. F = ma.',
    solutionBn: '১. প্রযুক্ত বল F = ভর (m) × ত্বরণ (a)\n২. বলের একক নিউটন (N) এবং ভরবেগের একক kg·m/s।\n৩. বল শূন্য হলে ত্বরণও শূন্য থাকবে।',
    solutionEn: '1. Applied force F = mass (m) × acceleration (a)\n2. SI unit of Force is Newton (N) and momentum is kg·m/s.\n3. If net force is zero, acceleration is also zero.',
    formula: 'F = m · a = dp / dt',
    chapterBn: 'অধ্যায় ৩: বল (Force)',
    chapterEn: 'Chapter 3: Force'
  },
  {
    id: 'scan-c9-math',
    classId: 'class-9',
    subject: 'Mathematics',
    subjectBn: 'গণিত (সাধারণ)',
    titleBn: '৯ম-১০ম গণিত: বীজগাণিতিক রাশি ও উৎপাদক',
    titleEn: 'Class 9-10 Math: Algebraic Expressions',
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    detectedTextBn: 'অনুশীলনী ৩.১: (a + b)² = a² + 2ab + b² এবং a³ + b³ = (a + b)(a² - ab + b²).',
    detectedTextEn: 'Exercise 3.1: (a + b)² = a² + 2ab + b² and a³ + b³ = (a + b)(a² - ab + b²).',
    solutionBn: '১. বীজগণিতের বর্গের সূত্র: (a + b)² = a² + 2ab + b²\n২. মান নির্ণয়ের সূত্র: a² + b² = (a + b)² - 2ab\n৩. উৎপাদকে বিশ্লেষণের ক্ষেত্রে কমন নিয়ে সূত্রে রূপান্তর করতে হয়।',
    solutionEn: '1. Square formula: (a + b)² = a² + 2ab + b²\n2. Value evaluation: a² + b² = (a + b)² - 2ab\n3. Factorization rule: Factor out common terms and simplify.',
    formula: 'a² + b² = (a + b)² - 2ab',
    chapterBn: 'অধ্যায় ৩: বীজগাণিতিক রাশি',
    chapterEn: 'Chapter 3: Algebraic Expressions'
  }
];
